# Generated by Django 5.2.4 on 2025-07-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="matricula",
            field=models.CharField(default=9513576549, max_length=10),
            preserve_default=False,
        ),
    ]
